version: "3.9"

services:
  app:
    build: .
    environment:
      - MONGODB=mongodb+srv://Videomovie:Kim0878744635@cluster0.bmqojm3.mongodb.net/?retryWrites=true&w=majority
    ports:
      - "8800:8800"
    volumes:
      - ./app-data:/app/data
    depends_on:
      - db

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Videomovie
      MONGO_INITDB_ROOT_PASSWORD: Kim0878744635
      MONGO_INITDB_DATABASE: test
    volumes:
      - ./db-data:/data/db
